<a href="https://colab.research.google.com/github/surendhar-code/GenAI-Masters/blob/main/Gen_AI_Text_Representation_and_Vectorization_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Bag of Words

In [7]:
import numpy as np
import pandas as pd

In [8]:
# creating dataframe
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})



In [9]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [11]:
bow = cv.fit_transform(df['text'])

In [12]:
# to know vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [13]:
# vectorized matrix using bag of words
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [14]:
# printing individual row vector matrix
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [15]:
# using this bow object for new data
cv.transform(["suren watch dswithbabby"]).toarray()

array([[0, 0, 0, 1, 0]])

In [16]:
X = bow.toarray()
y = df['output']

### Bag of Words using N - grams

In [17]:
# Bi grams

In [18]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [19]:
cv = CountVectorizer(ngram_range=(2,2))

In [20]:
bow_bi_gram = cv.fit_transform(df['text'])

In [21]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [22]:
bow_bi_gram.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

## TF-IDF (Term Frequency and Inverse Document Frequency)

In [23]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()


In [25]:
tfidf.fit_transform(df['text'])

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [27]:
tfidf_vec = tfidf.fit_transform(df['text']).toarray()

In [28]:
tfidf_vec

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])